### ISSUE TITLE
[BUG] Enhancecode

### ISSUE THREAD

**Issue by Soulivan71** [doggybootsy/enhancecodeblocks#3]
7bd1fe976ed34d5f31e0.js:218 [BetterDiscord] [Patcher] Could not fire after callback of renderAttachments for ECBlocks TypeError: Cannot read properties of undefined (reading 'attachments')
    at Object.eval [as callback] (EnhanceCodeBlocks.plugin.js:885:47)
    at n.renderAttachments (renderer.js:5707:41)
    at i.render (586c75f31fd6012f105d.js:544:567)
    at Ds (5e63cc1ef03bce4ba01d.js:1799:100)
    at Rs (5e63cc1ef03bce4ba01d.js:1798:890)
    at gu (5e63cc1ef03bce4ba01d.js:1839:100)
    at Ic (5e63cc1ef03bce4ba01d.js:1831:89)
    at mc (5e63cc1ef03bce4ba01d.js:1831:17)
    at hc (5e63cc1ef03bce4ba01d.js:1830:867)
    at ic (5e63cc1ef03bce4ba01d.js:1825:943)
    at v (5e63cc1ef03bce4ba01d.js:1943:904)
    at C (5e63cc1ef03bce4ba01d.js:1944:267)
    at R.<computed> (7bd1fe976ed34d5f31e0.js:67:1)
    at D (7bd1fe976ed34d5f31e0.js:66:764)
    at MessagePort.A (7bd1fe976ed34d5f31e0.js:66:823)
    
    Bug in console spam

**Comment by doggybootsy** [comment]
What version of discord do you use? I'm using discord stable and I do not have this problem.

**Comment by Soulivan71** [comment]
PTB

**Comment by Soulivan71** [comment]
Still here with last update

**Comment by doggybootsy** [comment]
I still haven't gotten this issue yet (But I can't test PTB). Do you have any other plugins that touch attachments?

**Comment by Soulivan71** [comment]
Hmmm I don't know

**Comment by Soulivan71** [comment]
![image](https://github.com/doggybootsy/enhancecodeblocks/assets/36502190/ac404462-0c2f-4ac3-9d0b-1057f64734ee)
![image](https://github.com/doggybootsy/enhancecodeblocks/assets/36502190/56b4c979-ffbe-4f7e-9b29-234d271580f6)

**Comment by doggybootsy** [comment]
hm, try disabling your plugins to see if it works

**Comment by Soulivan71** [comment]
:( Im not gonna try one by one Im sry but its tooo loong

**Comment by Soulivan71** [comment]
Update ?

**Comment by doggybootsy** [comment]
I can't provide much of a update because I haven't had this issue happen to me yet

**Comment by doggybootsy** [comment]
Closing this as there has been no updates towards this issue and because I still haven't gotten this issue.
