### ISSUE TITLE
Failed to load plugin after recent Discord breaking internal change

### ISSUE THREAD

**Issue by PythonTryHard** [doggybootsy/enhancecodeblocks#5]
**System**: 
- Ptb 241556 (6af2f93)
- Host 1.0.1040 x86 (38983)
- OpenAsar Nightly (eee9bab)
- Windows 11 22H2 (22621.1992)

**Reproduction**:
- Install `enhancecodeblocks` and enable the plugin

**Expected**:
Normal loading

**Actual**:
"An error was encountered while trying to load this plugin."

Crash log:
```
TypeError: import_highlight2.default.listLanguages is not a function
    at src/codeblock/changeLang.tsx (betterdiscord://plugins/EnhanceCodeBlocks.plugin.js:546:366)
    at eval (betterdiscord://plugins/EnhanceCodeBlocks.plugin.js:16:56)
    at src/codeblock/header.tsx (betterdiscord://plugins/EnhanceCodeBlocks.plugin.js:589:5)
    at eval (betterdiscord://plugins/EnhanceCodeBlocks.plugin.js:16:56)
    at src/codeblock/index.tsx (betterdiscord://plugins/EnhanceCodeBlocks.plugin.js:708:5)
    at eval (betterdiscord://plugins/EnhanceCodeBlocks.plugin.js:16:56)
    at src/index.tsx (betterdiscord://plugins/EnhanceCodeBlocks.plugin.js:920:5)
    at eval (betterdiscord://plugins/EnhanceCodeBlocks.plugin.js:16:56)
    at eval (betterdiscord://plugins/EnhanceCodeBlocks.plugin.js:954:19)
    at D.requireAddon (betterdiscord/renderer.js:5:33852)
```

Further information:
- [DevTool is currently fucked](https://www.reddit.com/r/discordapp/comments/17g642q/opening_inspect_element_automatically_restarts/) so I can't capture anything meaningful from the console.

**Comment by PythonTryHard** [comment]
Workaround found: Spam Ctrl-Shift-I during Discord's loading and swap to Console tab until fully loaded. Removed the plugin and manually reinstalled (download from `/dist`, dropped in plugins folder) to see if Console had anything interesting. Nope (the red are just Sentry stuffs)

![image](https://github.com/doggybootsy/enhancecodeblocks/assets/31789326/e4f5a531-c82a-4bc2-a816-4bf80c4d3974)

**Comment by doggybootsy** [comment]
Currently im just waiting until the devtools issue is resolved, then ill fix this

**Comment by PythonTryHard** [comment]
DevTool seems fixed now

**Comment by doggybootsy** [comment]
fixed

**Comment by D-Maxwell** [comment]
Still doesn't compile
```js
TypeError: import_highlight2.default.listLanguages is not a function
    at src/codeblock/changeLang.tsx (betterdiscord://plugins/EnhanceCodeBlocks.plugin.js:546:366)
    at eval (betterdiscord://plugins/EnhanceCodeBlocks.plugin.js:16:56)
    at src/codeblock/header.tsx (betterdiscord://plugins/EnhanceCodeBlocks.plugin.js:589:5)
    at eval (betterdiscord://plugins/EnhanceCodeBlocks.plugin.js:16:56)
    at src/codeblock/index.tsx (betterdiscord://plugins/EnhanceCodeBlocks.plugin.js:708:5)
    at eval (betterdiscord://plugins/EnhanceCodeBlocks.plugin.js:16:56)
    at src/index.tsx (betterdiscord://plugins/EnhanceCodeBlocks.plugin.js:920:5)
    at eval (betterdiscord://plugins/EnhanceCodeBlocks.plugin.js:16:56)
    at eval (betterdiscord://plugins/EnhanceCodeBlocks.plugin.js:954:19)
    at D.requireAddon (betterdiscord/renderer.js:5:33852)
```

**Comment by doggybootsy** [comment]
You need to download the plugin from github. The betterdiscord site takes a long time to update it
