### ISSUE TITLE
Thrown error

### ISSUE THREAD

**Issue by Test-Account666** [doggybootsy/enhancecodeblocks#9]
Just wanted you to inform you about an error being thrown:

<details>
  <summary>Error</summary>
  
```
73050.ed28c446e39c70b0c6c0.js:1 [BetterDiscord] [Patcher] Could not fire after callback of renderAttachments for ECBlocks TypeError: res.props.attachments is not iterable
    at Object.eval [as callback] (EnhanceCodeBlocks.plugin.js:976:47)
    at eK.<anonymous> (renderer.js:5:23163)
    at eK.render (8ffaad5d94980deea02d.js:1:306846)
    at o_ (44076.b5f9426088ebaff2b53a.js:12:914886)
    at og (44076.b5f9426088ebaff2b53a.js:12:914684)
    at u (44076.b5f9426088ebaff2b53a.js:12:956156)
    at sB (44076.b5f9426088ebaff2b53a.js:12:938190)
    at 44076.b5f9426088ebaff2b53a.js:12:938056
    at sF (44076.b5f9426088ebaff2b53a.js:12:938064)
    at sT (44076.b5f9426088ebaff2b53a.js:12:933101)
    at x (44076.b5f9426088ebaff2b53a.js:12:1125228)
    at A (44076.b5f9426088ebaff2b53a.js:12:1125758)
    at D.<computed> (44076.b5f9426088ebaff2b53a.js:1:500866)
    at M (44076.b5f9426088ebaff2b53a.js:1:500631)
    at MessagePort.k (44076.b5f9426088ebaff2b53a.js:1:500690)
t.<computed> @ 73050.ed28c446e39c70b0c6c0.js:1
(anonymous) @ VM10476 43455.8c79ce3e1753b38de4a4.js:23
_log @ renderer.js:5
err @ renderer.js:5
(anonymous) @ renderer.js:5
render @ 8ffaad5d94980deea02d.js:1
o_ @ 44076.b5f9426088ebaff2b53a.js:12
og @ 44076.b5f9426088ebaff2b53a.js:12
u @ 44076.b5f9426088ebaff2b53a.js:12
sB @ 44076.b5f9426088ebaff2b53a.js:12
(anonymous) @ 44076.b5f9426088ebaff2b53a.js:12
sF @ 44076.b5f9426088ebaff2b53a.js:12
sT @ 44076.b5f9426088ebaff2b53a.js:12
x @ 44076.b5f9426088ebaff2b53a.js:12
A @ 44076.b5f9426088ebaff2b53a.js:12
D.<computed> @ 44076.b5f9426088ebaff2b53a.js:1
M @ 44076.b5f9426088ebaff2b53a.js:1
k @ 44076.b5f9426088ebaff2b53a.js:1
```
  
</details>

**Comment by doggybootsy** [comment]
I pushed a fix couple days ago, you just need to download it from github

**Comment by Test-Account666** [comment]
Awesome!

Sorry for wasting your time then xd
